### ISSUE TITLE
Kernel-Headers missing

### ISSUE THREAD

**Issue by irreleph4nt** [StollD/fedora-linux-surface#6]
Hi,

Thank you for all the work you are putting into this! I am trying to use your packages on a Surface Go with Fedora 31 WS but have had limited success so far. For example:

I was trying to install your surface pen fix but running pip3 -U evdev fails as your repo does not provide kernel-headers.

**Comment by StollD** [comment]
Just install the default kernel-headers package from Fedora. I decided to not package the headers for the surface kernel specifically, because they would conflict with the default ones. And since the surface changes don't add any syscalls, they are probably identical anyways.

However, you should already have the default kernel headers installed (unless you uninstalled them). Did you run `pip3 -U evdev` as sudo? Because it works just fine for me.

**Comment by irreleph4nt** [comment]
This is on a fresh F31 install so I am positive headers are not installed by default (anymore?). The only downside to your approach might be that this way you always have to have the same version of the kernel availble in your repo and the official one, right? Because if you do not keep them in sync, you will have trouble building softwre from source like I had. Anyway, thank you for replying, this is good to be closed.
